a = int(input("Give me the first number: "))
b = int(input("Give me the second number: "))
print (f'Thank you!')
print (f"{a} + {b} = {a+b}")
print (f"{a} - {b} = {a-b}")
print (f"{a} / {b} = {a/b:.0f}")
print (f"{a} * {b} = {a*b}")